line-length = 120

[lint]
select = ["E", "F", "I"]

[format]
quote-style = "double"

[lint.isort]
known-first-party = ["app"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
force-sort-within-sections = false
