from sqlalchemy.orm import Session

from app.models import Interest, InterestCategory

INTEREST_CATALOG = {
    "Academics & Learning": [
        "Study groups",
        "Note-taking",
        "Exam prep",
        "Engineering",
        "Computer science",
        "Design & UX",
        "Data science",
        "AI & ML",
        "Economics & finance",
        "Marketing",
        "Law & public policy",
        "Psychology",
        "Medicine & health",
        "Architecture",
        "Humanities & liberal arts",
        "Research & hackathons",
        "Olympiads & competitions",
        "Scientific reading",
    ],
    "Sports & Fitness": [
        "Running",
        "Cycling",
        "Hiking",
        "Climbing",
        "Soccer",
        "Basketball",
        "Volleyball",
        "Tennis & padel",
        "Gym & calisthenics",
        "Yoga & Pilates",
        "Swimming",
        "E-sports",
        "Dance",
        "Martial arts",
    ],
    "Arts & Culture": [
        "Movies & series",
        "Music & concerts",
        "Podcasting",
        "Photography",
        "Video & editing",
        "Illustration & drawing",
        "Theatre",
        "Literature & book clubs",
        "Museums & exhibitions",
        "Crafts & DIY",
        "Fashion & style",
    ],
    "Tech, Maker & Gaming": [
        "Web & app development",
        "DevOps & cloud",
        "Cybersecurity",
        "Electronics & Arduino",
        "3D printing & fablab",
        "Robotics",
        "Product & tech startups",
        "No-code & automation",
        "Video games",
        "Game design",
        "VR & AR",
    ],
    "Travel & Languages": [
        "Exchange & Erasmus",
        "Budget travel",
        "Backpacking",
        "English language",
        "French language",
        "German language",
        "Italian language",
        "Portuguese language",
        "Swedish language",
        "Catalan & Spanish",
        "Other languages",
        "Language exchange & tandem",
        "International culture",
    ],
    "Volunteering & Sustainability": [
        "Social volunteering",
        "Mentoring",
        "Donations & NGOs",
        "Sustainability",
        "Zero-waste lifestyle",
        "Urban gardening",
        "Beach & mountain clean-ups",
        "Environmental education",
    ],
    "Food, Coffee & Lifestyle": [
        "Coffee shops & study spots",
        "Brunch",
        "Home cooking",
        "Vegetarian & vegan",
        "Nutrition",
        "Baking & pastry",
        "Coffee & tea",
        "Craft beer (18+)",
        "Wine tasting (18+)",
        "Minimalism & organization",
    ],
    "Career & Entrepreneurship": [
        "Job board",
        "Internships",
        "CV & LinkedIn",
        "Consulting case prep",
        "Business cases",
        "Entrepreneurship & startups",
        "Pitching & incubators",
        "Networking & meetups",
        "Career fairs",
    ],
    "Housing & Daily Life": [
        "Room hunting",
        "Roommates",
        "Low-cost decor",
        "Second-hand furniture",
        "Repairs & DIY",
        "Moving & logistics",
        "Expense management",
        "Insurance",
        "Home internet",
    ],
    "Social, Events & Nightlife": [
        "Campus events",
        "Dating",
        "Theme parties",
        "Board games",
        "Role-playing games",
        "Trivia & quiz nights",
        "Student clubs & associations",
    ],
    "Wellbeing & Mindfulness": [
        "Mental health",
        "Mindfulness & meditation",
        "Time management & focus",
        "Bullet journaling",
        "Study-life balance",
        "Digital detox",
    ],
    "Finance & Investing (students)": [
        "Personal budgeting",
        "Saving money",
        "Stocks & ETFs basics",
        "Crypto (educational)",
        "Ethical finance",
        "Scholarships & grants",
    ],
    "Mobility & Carpool": [
        "Daily carpool",
        "Weekend ridesharing",
        "Electric bike",
        "Scooter commuting",
        "Public transport",
        "Road trips",
    ],
}


def seed_interests(db: Session) -> None:
    """Create the default catalog of interest categories and interests."""
    for category_name, interests in INTEREST_CATALOG.items():
        category = db.query(InterestCategory).filter_by(name=category_name).first()
        if not category:
            category = InterestCategory(name=category_name)
            db.add(category)
            db.flush()

        existing = {interest.name for interest in category.interests}
        for interest_name in interests:
            if interest_name not in existing:
                db.add(Interest(name=interest_name, category=category))
