"""initial_schema

Revision ID: 091e9af0855b
Revises:
Create Date: 2025-12-14 23:20:32.854070

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "091e9af0855b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=120), nullable=True),
        sa.Column("channel_type", sa.String(length=50), nullable=False),
        sa.Column(
            "category",
            sa.Enum("GENERAL", "ENGINEERING", "SCIENCES", "BUSINESS", "ARTS", "MEDICINE", name="channelcategory"),
            nullable=True,
        ),
        sa.Column("required_role_read", sa.Enum("ADMIN", "SELLER", "RECRUITER", "BASIC", name="role"), nullable=False),
        sa.Column("required_role_write", sa.Enum("ADMIN", "SELLER", "RECRUITER", "BASIC", name="role"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("channel_logo", sa.String(length=2048), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_channel_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_required_role_read"), ["required_role_read"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_required_role_write"), ["required_role_write"], unique=False)

    op.create_table(
        "housing_amenity",
        sa.Column("code", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "housing_category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "interest_category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "item_category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "terms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "university",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "faculty",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("university_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interest",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["interest_category.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("faculty_id", sa.UUID(), nullable=True),
        sa.Column("year_of_study", sa.Integer(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("room_number", sa.String(length=20), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("referral_code", sa.String(length=5), nullable=False),
        sa.Column("referred_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["faculty.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referred_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referral_code"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "channel_bans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("motive", sa.String(length=255), nullable=False),
        sa.Column("duration", sa.Interval(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("banned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("banned_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["banned_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel_members",
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("channel_id", "user_id"),
    )
    op.create_table(
        "channel_unbans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("motive", sa.String(length=255), nullable=False),
        sa.Column("unbanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unbanned_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unbanned_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("connection_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("storage_type", sa.String(length=50), nullable=False),
        sa.Column("file_data", sa.LargeBinary(), nullable=True),
        sa.Column("uploader_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_files_uploader_id"), ["uploader_id"], unique=False)

    op.create_table(
        "housing_offer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("area", sa.Numeric(), nullable=False),
        sa.Column("offer_valid_until", sa.Date(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("deposit", sa.Numeric(), nullable=True),
        sa.Column("num_rooms", sa.Integer(), nullable=True),
        sa.Column("num_bathrooms", sa.Integer(), nullable=True),
        sa.Column("gender_preference", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("furnished", sa.Boolean(), nullable=False),
        sa.Column("utilities_included", sa.Boolean(), nullable=False),
        sa.Column("internet_included", sa.Boolean(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("floor_number", sa.Integer(), nullable=True),
        sa.Column("distance_from_campus", sa.String(length=100), nullable=True),
        sa.Column("utilities_cost", sa.Numeric(), nullable=True),
        sa.Column("utilities_description", sa.Text(), nullable=True),
        sa.Column("contract_type", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("posted_date", sa.DateTime(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["housing_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("posted_date", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["item_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.create_index("ix_item_location", ["location"], unique=False)
        batch_op.create_index("ix_item_price", ["price"], unique=False)
        batch_op.create_index("ix_item_search", ["title", "description"], unique=False)
        batch_op.create_index("ix_item_status", ["status"], unique=False)

    op.create_table(
        "job_offer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("workplace_type", sa.String(length=50), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("salary_min", sa.Numeric(), nullable=True),
        sa.Column("salary_max", sa.Numeric(), nullable=True),
        sa.Column("salary_period", sa.String(length=20), nullable=False),
        sa.Column("company_name", sa.String(length=100), nullable=False),
        sa.Column("company_description", sa.Text(), nullable=True),
        sa.Column("company_website", sa.String(length=255), nullable=True),
        sa.Column("company_employee_count", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column("parent_message_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "password_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_password_history_user_id"), ["user_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reported_by_id", sa.UUID(), nullable=False),
        sa.Column("reported_user_id", sa.UUID(), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("content_id", sa.String(length=255), nullable=False),
        sa.Column("content_title", sa.String(length=500), nullable=True),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reported_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reported_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_interest",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("interest_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["interest_id"], ["interest.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "interest_id", name="uq_user_interest"),
    )
    with op.batch_alter_table("user_interest", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_interest_interest_id"), ["interest_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_interest_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_like",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.Enum("HOUSING_OFFER", "JOB_OFFER", "ITEM", name="liketargettype"), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="like_status_enum"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "target_id", "target_type"),
    )
    with op.batch_alter_table("user_like", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_like_status"), ["status"], unique=False)

    op.create_table(
        "user_terms_acceptance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("terms_id", sa.UUID(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["terms_id"],
            ["terms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user1_id", sa.UUID(), nullable=False),
        sa.Column("user2_id", sa.UUID(), nullable=False),
        sa.Column("housing_offer_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["housing_offer_id"],
            ["housing_offer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user1_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user2_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user1_id", "user2_id", "housing_offer_id", name="uq_conversation"),
    )
    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversation_housing_offer_id"), ["housing_offer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversation_user1_id"), ["user1_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversation_user2_id"), ["user2_id"], unique=False)

    op.create_table(
        "file_association",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("file_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("file_association", schema=None) as batch_op:
        batch_op.create_index("ix_file_association_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("ix_file_association_file", ["file_id"], unique=False)

    op.create_table(
        "housing_offer_amenity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("amenity_code", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["amenity_code"], ["housing_amenity.code"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["offer_id"], ["housing_offer.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("offer_id", "amenity_code", name="uq_offer_amenity"),
    )
    op.create_table(
        "job_application",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_offer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "job_id"),
    )
    op.create_table(
        "saved_job",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("saved_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_offer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "job_id"),
    )
    op.create_table(
        "conversation_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_message", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversation_message_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversation_message_sender_id"), ["sender_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_message_sender_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_message_conversation_id"))

    op.drop_table("conversation_message")
    op.drop_table("saved_job")
    op.drop_table("job_application")
    op.drop_table("housing_offer_amenity")
    with op.batch_alter_table("file_association", schema=None) as batch_op:
        batch_op.drop_index("ix_file_association_file")
        batch_op.drop_index("ix_file_association_entity")

    op.drop_table("file_association")
    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_user2_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_user1_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_housing_offer_id"))

    op.drop_table("conversation")
    op.drop_table("user_terms_acceptance")
    with op.batch_alter_table("user_like", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_like_status"))

    op.drop_table("user_like")
    with op.batch_alter_table("user_interest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_interest_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_interest_interest_id"))

    op.drop_table("user_interest")
    op.drop_table("reports")
    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_history_user_id"))

    op.drop_table("password_history")
    op.drop_table("message")
    op.drop_table("job_offer")
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_index("ix_item_status")
        batch_op.drop_index("ix_item_search")
        batch_op.drop_index("ix_item_price")
        batch_op.drop_index("ix_item_location")

    op.drop_table("item")
    op.drop_table("housing_offer")
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_uploader_id"))

    op.drop_table("files")
    op.drop_table("connections")
    op.drop_table("channel_unbans")
    op.drop_table("channel_members")
    op.drop_table("channel_bans")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    op.drop_table("interest")
    op.drop_table("faculty")
    op.drop_table("university")
    op.drop_table("terms")
    op.drop_table("item_category")
    op.drop_table("interest_category")
    op.drop_table("housing_category")
    op.drop_table("housing_amenity")
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_required_role_write"))
        batch_op.drop_index(batch_op.f("ix_channel_required_role_read"))
        batch_op.drop_index(batch_op.f("ix_channel_name"))
        batch_op.drop_index(batch_op.f("ix_channel_category"))

    op.drop_table("channel")
    # ### end Alembic commands ###
