"""add_user_ban_fields

Revision ID: 3ef72cbe3fbf
Revises: 091e9af0855b
Create Date: 2025-12-30 19:41:16.815520

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ef72cbe3fbf"
down_revision: Union[str, Sequence[str], None] = "091e9af0855b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("channel_bans", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("channel_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("banned_by", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=True)

    with op.batch_alter_table("channel_members", schema=None) as batch_op:
        batch_op.alter_column("channel_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("channel_unbans", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("channel_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("unbanned_by", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=True)

    with op.batch_alter_table("connections", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user1_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user2_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("housing_offer_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=True)

    with op.batch_alter_table("conversation_message", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("conversation_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("sender_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("faculty", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("university_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("file_association", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("file_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("entity_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("uploader_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("housing_category", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("housing_offer", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("category_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("housing_offer_amenity", schema=None) as batch_op:
        batch_op.alter_column("offer_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("seller_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("category_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("item_category", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("job_application", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("job_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("job_offer", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("channel_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("parent_message_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=True)

    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("reported_by_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("reported_user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("reviewed_by_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=True)

    with op.batch_alter_table("saved_job", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("job_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("terms", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("university", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("banned_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("banned_until", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("ban_reason", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("banned_by_id", sa.UUID(), nullable=True))
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("faculty_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=True)
        batch_op.alter_column("referred_by_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=True)
        batch_op.create_foreign_key("fk_user_banned_by_id", "user", ["banned_by_id"], ["id"])

    with op.batch_alter_table("user_interest", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("user_like", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("target_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    with op.batch_alter_table("user_terms_acceptance", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
        batch_op.alter_column("terms_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_terms_acceptance", schema=None) as batch_op:
        batch_op.alter_column("terms_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("user_like", schema=None) as batch_op:
        batch_op.alter_column("target_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("user_interest", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_banned_by_id", type_="foreignkey")
        batch_op.alter_column("referred_by_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=True)
        batch_op.alter_column("faculty_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=True)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.drop_column("banned_by_id")
        batch_op.drop_column("ban_reason")
        batch_op.drop_column("banned_until")
        batch_op.drop_column("banned_at")

    with op.batch_alter_table("university", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("terms", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("saved_job", schema=None) as batch_op:
        batch_op.alter_column("job_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.alter_column("reviewed_by_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=True)
        batch_op.alter_column("reported_user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("reported_by_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column("parent_message_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("channel_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("job_offer", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("job_application", schema=None) as batch_op:
        batch_op.alter_column("job_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("item_category", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column("category_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("seller_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("housing_offer_amenity", schema=None) as batch_op:
        batch_op.alter_column("offer_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("housing_offer", schema=None) as batch_op:
        batch_op.alter_column("category_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("housing_category", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("uploader_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("file_association", schema=None) as batch_op:
        batch_op.alter_column("entity_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("file_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("faculty", schema=None) as batch_op:
        batch_op.alter_column("university_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("conversation_message", schema=None) as batch_op:
        batch_op.alter_column("sender_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("conversation_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.alter_column("housing_offer_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=True)
        batch_op.alter_column("user2_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("user1_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("connections", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("channel_unbans", schema=None) as batch_op:
        batch_op.alter_column("unbanned_by", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("channel_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("channel_members", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("channel_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("channel_bans", schema=None) as batch_op:
        batch_op.alter_column("banned_by", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("channel_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)

    # ### end Alembic commands ###
